const esc = (v = '') => String(v).replace(/[&<>"']/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[c]);
const link = (u) => /^https?:\/\//i.test(u || '') ? u : '#';
function card(a) {
  const refs = (a.crossSources || []).slice(0, 4).map((s) => `<a href="${esc(link(s.url))}" style="color:#8ab4f8">${esc(s.source)}</a>`).join(' · ');
  return `<article style="background:#182033;border:1px solid #2c3853;border-radius:14px;padding:18px;margin:14px 0"><div>${a.tags.map((t) => `<span style="display:inline-block;background:${t.includes('中国') ? '#b42318' : t.includes('美国') ? '#175cd3' : '#344054'};color:#fff;border-radius:12px;padding:3px 9px;margin:0 6px 6px 0;font-size:12px">【${esc(t)}】</span>`).join('')}</div><h3 style="margin:8px 0;color:#f2f4f7;font-size:19px;line-height:1.45"><a href="${esc(link(a.url))}" style="color:#f2f4f7;text-decoration:none">${esc(a.titleZh)}</a></h3><div style="color:#fdb022;font-weight:bold">热点 ${a.score}/100</div><p style="color:#d0d5dd;line-height:1.7">${esc(a.summaryZh)}</p><p style="color:#b9d4ff;line-height:1.6"><b>为什么重要：</b>${esc(a.whyImportant)}</p>${a.isContinuation ? '<p style="color:#fdb022"><b>本次新增进展：</b>与近 7 日同一事件相比，标题或公开摘要出现新信息。</p>' : ''}<p style="color:#98a2b3;font-size:12px">${esc(a.source)} · ${esc(new Date(a.publishedAt).toLocaleString('zh-CN'))}</p><p style="color:#98a2b3;font-size:12px">交叉来源：${refs || '暂无其他独立来源'}</p></article>`;
}
const section = (title, items) => `<h2 style="color:#fff;border-left:4px solid #5b8def;padding-left:10px;margin-top:30px">${esc(title)}</h2>${items.length ? items.map(card).join('') : '<p style="color:#98a2b3">过去 24 小时暂无达到质量阈值的条目。</p>'}`;
export function renderHtml(report) {
  return `<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width"></head><body style="margin:0;background:#0b1020;font-family:Arial,'Microsoft YaHei',sans-serif"><div style="max-width:720px;margin:auto;padding:20px"><header><h1 style="color:#fff">全球时政热点日报</h1><p style="color:#98a2b3">${esc(report.date)} · 过去 24 小时公开新闻摘要</p><div style="background:#101828;color:#e4e7ec;border-radius:12px;padding:16px"><b>今日一句话总览：</b>${esc(report.overview)}</div></header>${section('全球焦点', report.global)}${section('中国重点', report.china)}${section('美国重点', report.usa)}${section('今日观察', report.watch)}<footer style="color:#667085;font-size:12px;line-height:1.6;margin-top:28px;border-top:1px solid #344054;padding-top:16px">数据来自 GDELT 与公开 RSS。摘要仅基于公开标题及摘要自动生成，不构成投资、法律或安全建议。突发事件可能快速变化，请以原始来源和后续官方信息为准。</footer></div></body></html>`;
}
